// Code generated by protoc-gen-go.
// source: proxy.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proxy.proto

It has these top-level messages:
	WeedFileRequest
	WeedFileResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type WeedFileRequest struct {
	Fid string `protobuf:"bytes,1,opt,name=Fid,json=fid" json:"Fid,omitempty"`
}

func (m *WeedFileRequest) Reset()                    { *m = WeedFileRequest{} }
func (m *WeedFileRequest) String() string            { return proto1.CompactTextString(m) }
func (*WeedFileRequest) ProtoMessage()               {}
func (*WeedFileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type WeedFileResponse struct {
	FileContent string `protobuf:"bytes,1,opt,name=FileContent,json=fileContent" json:"FileContent,omitempty"`
}

func (m *WeedFileResponse) Reset()                    { *m = WeedFileResponse{} }
func (m *WeedFileResponse) String() string            { return proto1.CompactTextString(m) }
func (*WeedFileResponse) ProtoMessage()               {}
func (*WeedFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*WeedFileRequest)(nil), "proto.WeedFileRequest")
	proto1.RegisterType((*WeedFileResponse)(nil), "proto.WeedFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for WeedProxy service

type WeedProxyClient interface {
	GetFileContent(ctx context.Context, in *WeedFileRequest, opts ...grpc.CallOption) (*WeedFileResponse, error)
}

type weedProxyClient struct {
	cc *grpc.ClientConn
}

func NewWeedProxyClient(cc *grpc.ClientConn) WeedProxyClient {
	return &weedProxyClient{cc}
}

func (c *weedProxyClient) GetFileContent(ctx context.Context, in *WeedFileRequest, opts ...grpc.CallOption) (*WeedFileResponse, error) {
	out := new(WeedFileResponse)
	err := grpc.Invoke(ctx, "/proto.WeedProxy/GetFileContent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WeedProxy service

type WeedProxyServer interface {
	GetFileContent(context.Context, *WeedFileRequest) (*WeedFileResponse, error)
}

func RegisterWeedProxyServer(s *grpc.Server, srv WeedProxyServer) {
	s.RegisterService(&_WeedProxy_serviceDesc, srv)
}

func _WeedProxy_GetFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeedFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeedProxyServer).GetFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WeedProxy/GetFileContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeedProxyServer).GetFileContent(ctx, req.(*WeedFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WeedProxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WeedProxy",
	HandlerType: (*WeedProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFileContent",
			Handler:    _WeedProxy_GetFileContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("proxy.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xaf,
	0xa8, 0xd4, 0x03, 0x92, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x4a, 0x49, 0x99, 0x8b, 0x3f, 0x3c, 0x35,
	0x35, 0xc5, 0x2d, 0x33, 0x27, 0x35, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x80, 0x8b,
	0xd9, 0x2d, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x39, 0x2d, 0x33, 0x45, 0xc9,
	0x84, 0x4b, 0x00, 0xa1, 0xa8, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x81, 0x8b, 0x1b, 0xc4,
	0x77, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x81, 0xaa, 0xe6, 0x4e, 0x43, 0x08, 0x19, 0x05, 0x70,
	0x71, 0x82, 0x74, 0x05, 0x80, 0x2c, 0x15, 0x72, 0xe6, 0xe2, 0x73, 0x4f, 0x2d, 0x41, 0xd2, 0x21,
	0x24, 0x06, 0x71, 0x88, 0x1e, 0x9a, 0xf5, 0x52, 0xe2, 0x18, 0xe2, 0x10, 0x1b, 0x95, 0x18, 0x92,
	0xd8, 0xc0, 0x32, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x59, 0xfa, 0xf4, 0xc9, 0x00,
	0x00, 0x00,
}
