# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proxy.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0bproxy.proto\x12\x05proto\"\x1e\n\x0fWeedFileRequest\x12\x0b\n\x03\x46id\x18\x01 \x01(\t\"\'\n\x10WeedFileResponse\x12\x13\n\x0b\x46ileContent\x18\x01 \x01(\t2P\n\tWeedProxy\x12\x43\n\x0eGetFileContent\x12\x16.proto.WeedFileRequest\x1a\x17.proto.WeedFileResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WEEDFILEREQUEST = _descriptor.Descriptor(
  name='WeedFileRequest',
  full_name='proto.WeedFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Fid', full_name='proto.WeedFileRequest.Fid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_WEEDFILERESPONSE = _descriptor.Descriptor(
  name='WeedFileResponse',
  full_name='proto.WeedFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FileContent', full_name='proto.WeedFileResponse.FileContent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['WeedFileRequest'] = _WEEDFILEREQUEST
DESCRIPTOR.message_types_by_name['WeedFileResponse'] = _WEEDFILERESPONSE

WeedFileRequest = _reflection.GeneratedProtocolMessageType('WeedFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _WEEDFILEREQUEST,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proto.WeedFileRequest)
  ))
_sym_db.RegisterMessage(WeedFileRequest)

WeedFileResponse = _reflection.GeneratedProtocolMessageType('WeedFileResponse', (_message.Message,), dict(
  DESCRIPTOR = _WEEDFILERESPONSE,
  __module__ = 'proxy_pb2'
  # @@protoc_insertion_point(class_scope:proto.WeedFileResponse)
  ))
_sym_db.RegisterMessage(WeedFileResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class WeedProxyStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetFileContent = channel.unary_unary(
          '/proto.WeedProxy/GetFileContent',
          request_serializer=WeedFileRequest.SerializeToString,
          response_deserializer=WeedFileResponse.FromString,
          )


  class WeedProxyServicer(object):

    def GetFileContent(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_WeedProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetFileContent': grpc.unary_unary_rpc_method_handler(
            servicer.GetFileContent,
            request_deserializer=WeedFileRequest.FromString,
            response_serializer=WeedFileResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proto.WeedProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaWeedProxyServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetFileContent(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaWeedProxyStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetFileContent(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetFileContent.future = None


  def beta_create_WeedProxy_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('proto.WeedProxy', 'GetFileContent'): WeedFileRequest.FromString,
    }
    response_serializers = {
      ('proto.WeedProxy', 'GetFileContent'): WeedFileResponse.SerializeToString,
    }
    method_implementations = {
      ('proto.WeedProxy', 'GetFileContent'): face_utilities.unary_unary_inline(servicer.GetFileContent),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_WeedProxy_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('proto.WeedProxy', 'GetFileContent'): WeedFileRequest.SerializeToString,
    }
    response_deserializers = {
      ('proto.WeedProxy', 'GetFileContent'): WeedFileResponse.FromString,
    }
    cardinalities = {
      'GetFileContent': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'proto.WeedProxy', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
