# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proxy_pb2 as proxy__pb2


class WeedProxyStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetFileContent = channel.unary_unary(
        '/proto.WeedProxy/GetFileContent',
        request_serializer=proxy__pb2.WeedFileRequest.SerializeToString,
        response_deserializer=proxy__pb2.WeedFileResponse.FromString,
        )


class WeedProxyServicer(object):

  def GetFileContent(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WeedProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetFileContent': grpc.unary_unary_rpc_method_handler(
          servicer.GetFileContent,
          request_deserializer=proxy__pb2.WeedFileRequest.FromString,
          response_serializer=proxy__pb2.WeedFileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.WeedProxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
